### ISSUE TITLE
Don't expose IDs in URLs as slugs

### ISSUE THREAD

**Issue by ags** [ags/gendo#11]
Generate unique slug tokens for resource slugs, maybe 6 or 7 characters, hex or sha1. Just something more obfuscated than the ID.
- [ ] Apps
- [ ] Sources
- [ ] Transactions

**Comment by yesterdays-vigilante** [comment]
Right, two points:
- I'm not sure how making slug tokens (in a reliable fashion) would obfusticate the page. I suppose we could have a hacker news-esque x-minute turnaround per hash, but any other way would just lead to people being able to work out the _token_ for the object, which could be searched on just as easily as the ID (well, one level less easily because you'll need to know what the column is called, but...). I may, of course, be missing something obvious, or just generally an idiot :P.
- If we're looking at just increasing the max potential objects (over two billion or whatever MAX_INT is in postgres), why not just migrate the ids for the concerned fields (probably only transactions, really) to bigints? That way we shouldn't need to change any other code. Again, may be missing something.

**Comment by ags** [comment]
So there's really two issues here - the slugs and the ID limit.

The slugs aren't intended as strong obfuscation, just that I don't really want to expose IDs directly - "transactions/d4e7021" seems nicer than "transactions/2". Purely an aesthetic thing, I guess. Storing the sha1 of the app id and transaction id for a transaction slug (for example) and just using the first 7 chars in the `to_param` method. The full sha1 ought not to collide, but the substring might - scoping by app in this case would handle that, I expect. Alternately, ditch the aesthetic and just use ID, or maybe add more than just id (like apps have name and id currently). That would be alright too. I'm actually leaning toward that now, calculating and storing a hash is a bit of not particularly well justified overhead. Thoughts?

For the ids, I reckon [bigserial](http://www.postgresql.org/docs/9.2/static/datatype-numeric.html) - apparently the same thing as bigint, but you don't have to specify the sequence for nextval yourself. I expect transactions to be dwarfed by the event types, but sources, apps, access tokens and users are likely fine with 2 billion ;)

**Comment by ags** [comment]
Yeah, straight ID or ID and a parameterised string where appropriate is fine. Calling this closed unless anyone has objections.
